### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by sofiter** [thegreatsunra/intkey-client-js#1]
Hello, I thought that your app had a gui, I found out that it doesn't. Anyway, I tried to run it and I am getting the following error

> $ node index.js --name foo --verb set --value 42
> /home/st/intkey-client-js-develop/index.js:1
> (function (exports, require, module, __filename, __dirname) { const { EnclaveFactory } = require('./enclave')
>                                                                     ^
> 
> SyntaxError: Unexpected token {
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:374:25)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Function.Module.runMain (module.js:442:10)
>     at startup (node.js:136:18)
>     at node.js:966:3

**Comment by thegreatsunra** [comment]
I tested this with the latest release but was unable to reproduce. It appears your version of Node isn't correctly parsing the syntax for object destructuring.

What version Node are you running?

**Comment by thegreatsunra** [comment]
Closing this due to inactivity.  💤
